### ISSUE TITLE
"Issues" link in Modrinth page for mod is incorrect

### ISSUE THREAD

**Issue by James103** [AquUpd/BrownBear#1]
The issue link in the [Modrinth page](https://modrinth.com/mod/grizzly-bear) for the mod is incorrect. It should be https://github.com/AquUpd/GrizzlyBearMob/issues (same as in the [Curseforge page](https://www.curseforge.com/minecraft/mc-mods/grizzly-bear)), but it currently points to https://www.curseforge.com/minecraft/mc-mods/grizzly-bear/settings/issues, which is a privileged-access link, causing regular users to get redirected to the Curseforge / Twitch sign in page.

**Comment by Ivan-Khar** [comment]
True, thanks!
